name: Deploy addon to beamup

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  verify-version:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  beamup-deploy:
    needs: verify-version
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install beamup
        run: npm install beamup-cli -g
      - name: Create beamup json
        run: |
          touch ~/beamup-config.json
          echo ${{ secrets.BEAMUP_CONFIG_JSON }} > ~/beamup-config.json
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Add beamup remote
        run: git remote add beamup ${{ secrets.BEAMUP_REMOTE }}
      - name: Add private key
        run: |
          touch ~/.ssh/id_rsa
          echo ${{ secrets.SSH_KEY }}
          chmod 400 ~/.ssh/id_rsa
      - name: Deploy addon to beamup
        run: git push HEAD:master --force


